SCREEN_TITLE = "Arcade game"
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 960
CAMERA_WIDTH = 700
CAMERA_HEIGHT = 500

SPRITE_SCALING = 0.5
SPRITE_PIXEL_SIZE = 32
SPRITE_NATIVE_SIZE = 32
SPRITE_SIZE = int(SPRITE_NATIVE_SIZE * SPRITE_SCALING)
MAP_WIDTH = 120
MAP_HEIGHT = 100

# Movement speed of player, in pixels per frame and is multiplied by delta_time
MOVEMENT_SPEED = 75
